blank_issues_enabled: true
contact_links: []

issue_templates:
  - name: Bug report
    description: Report a bug with RichLinks
    labels: ["bug"]
    file: bug_report.yml

  - name: Feature request
    description: Suggest a feature or improvement for RichLinks
    labels: ["enhancement"]
    file: feature_request.yml
